---
title: "stats-101a-project-markdown"
author: "Naren Akurati"
date: "3/11/2018"
output: pdf_document
---

```{r}
#data cleanup
happiness_data <- read.table("Happiness.txt", header = TRUE)
head(happiness_data)

happiness_data$Household[happiness_data$Household == 8 | happiness_data$Household == 9] <- NA

happiness_data$Health[happiness_data$Health == 8 | happiness_data$Health == 9 |  happiness_data$Health == 0] <- NA
happiness_data$Health[happiness_data$Health == 1] <- 400
happiness_data$Health[happiness_data$Health == 2] <- 300
happiness_data$Health[happiness_data$Health == 3] <- 2
happiness_data$Health[happiness_data$Health == 4] <- 1
happiness_data$Health[happiness_data$Health == 400] <- 4
happiness_data$Health[happiness_data$Health == 300] <- 3

happiness_data$OwnHome[happiness_data$OwnHome == 0 | happiness_data$OwnHome == 8 | happiness_data$OwnHome == 9] <- NA

happiness_data$Instagram[happiness_data$Instagram == 0 | happiness_data$Instagram == 8 | happiness_data$Instagram == 9] <- NA

happiness_data$Marital[happiness_data$Marital == 9] <- NA

happiness_data$Age[happiness_data$Age == 89 | happiness_data$Age == 98 | happiness_data$Age == 99] <- NA

happiness_data$Children[happiness_data$Children == 8 | happiness_data$Children == 9] <- NA

happiness_data$Education[happiness_data$Education == 97 | happiness_data$Education == 98 | happiness_data$Education == 99] <- NA

happiness_data$JobSat[happiness_data$JobSat == 0 | happiness_data$JobSat == 8 | happiness_data$JobSat == 9] <- NA

happiness_data$Income[happiness_data$Income == 0 | happiness_data$Income == 999998 | happiness_data$Income == 999999] <- NA

happiness_data$WorkHrs[happiness_data$WorkHrs == -1 | happiness_data$WorkHrs == 998 | happiness_data$WorkHrs == 999] <- NA

happiness_data$Happy[happiness_data$Happy == 0 | happiness_data$Happy == 8 | happiness_data$Happy == 9] <- NA

happiness_data$Happy[happiness_data$Happy == 1] <- 100
happiness_data$Happy[happiness_data$Happy == 3] <- 1
happiness_data$Happy[happiness_data$Happy == 100] <- 3
````

````{r}
#exploring data
pairs(happiness_data[, -c(1,2,3,4,5,6,8,10)], gap=0.4,cex.labels=1.5)

m1 <- lm(happiness_data$Happy ~ happiness_data$Age + happiness_data$Education + happiness_data$Income + happiness_data$WorkHrs)

summary(m1)

m2 <- lm(happiness_data$Happy ~ happiness_data$Income)
plot(happiness_data$Happy ~ happiness_data$Income)
summary(m2)

#adding factors/levels
HappyCat <- factor(happiness_data$Happy)
levels(HappyCat)

#m4 <- lm(HappyCat ~ happiness_data$Income)
#summary(m4)
#plot(HappyCat ~ happiness_data$Income)

#m5 <- lm(happiness_data$Income ~ HappyCat)
#summary(m5)
#plot(happiness_data$Income ~ HappyCat)

#transforming linear income
mean_income <- mean(happiness_data$Income, na.rm=TRUE)
tIncome <- happiness_data$Income/mean_income
m6 <- lm(happiness_data$Happy ~ tIncome)
summary(m6)

#transforming inverse income
inverse_income <- 1/(happiness_data$Income)
m7 <- lm(happiness_data$Happy ~ inverse_income)
summary(m7)
```

```{r}
library(alr3)
m1 <- lm(happiness_data$Happy ~ factor(happiness_data$Household) + factor(happiness_data$OwnHome) + happiness_data$Instagram + factor(happiness_data$Marital) + happiness_data$Children + happiness_data$Education + factor(happiness_data$JobSat) + happiness_data$Income)
inverse.response.plot(m1,key=TRUE)


m2 <- lm((happiness_data$Happy)^0.396 ~ factor(happiness_data$Household) + factor(happiness_data$OwnHome) + happiness_data$Instagram + factor(happiness_data$Marital) + happiness_data$Children + happiness_data$Education + factor(happiness_data$JobSat) + happiness_data$Income)
summary(m2)

par(mfrow=c(2,2))
plot(m2)

anova(m2)

```


```{r}
#naren
#testing the significance of Children predictor variable
plot(happiness_data$Happy ~ happiness_data$Children)
m8 <- lm(happiness_data$Happy ~ happiness_data$Children)
summary(m8)
#it seems children and happiness have almost no correlation. we might be able to remove this one

#testing the significance of Education predictor variable
m9 <- lm(happiness_data$Happy ~ happiness_data$Education)
summary(m9)
plot(m9)
plot(happiness_data$Happy ~ factor(happiness_data$Education))
#judging from the linearity of the residuals plot, it does not seem education needs a transformation

#ignore below
  # inverseEducation <- 1/(happiness_data$Education)
  # inverseEducation[which(is.nan(inverseEducation))] = NA
  # inverseEducation[which(inverseEducation==Inf)] = NA
  # m9 <- lm(happiness_data$Happy ~ inverseEducation)
  # summary(m9)
  
  # inverseLogEducation <- (happiness_data$Education)^0.25
  # inverseLogEducation[which(is.nan(inverseLogEducation))] = NA
  # inverseLogEducation[which(inverseLogEducation==Inf)] = NA
  # m10 <- lm(happiness_data$Happy ~ inverseLogEducation)
  # summary(m10)
  # plot(m10)
```

```{r}
#jeremy first commit
```